### ISSUE TITLE
4.6.2 doesnt sync

### ISSUE THREAD

**Issue by Ericsan67** [VitaeTeam/Vitae#102]
After installing the 4.6.2 wallet is wont sync. My blocks stick at block 2052231 and freezes. what to do?

**Comment by osizadmin** [comment]
We have used both 4.6.2 and 4.5.1 wallet packages. My wallet block not sync after 2061910 block. Kindly check and advise us how to resolve this issue.

**Comment by 2a5A1Ghu1** [comment]
I am not able to reproduce this issue
