### ISSUE TITLE
no syncronisation on vitae core wallet   V: 4.5.1

### ISSUE THREAD

**Issue by gahartenstein** [VitaeTeam/Vitae#104]
hello, 

can you help?  no syncronisation
![IMG_5858](https://user-images.githubusercontent.com/80691925/111159096-04aeff00-8599-11eb-9684-9889d7437903.jpg)

**Comment by vitaeuk1** [comment]
Did you get any help ??

**Comment by squidicuzz** [comment]
Use version 4.6.2 now.

**Comment by gahartenstein** [comment]
Thank you. yes i did 4.6.2

 

We check in the moment  my computer if there is a problem.

 

I will come back to you if the problrm goes on.

 

Bet regards Günther

 

Von: squidicuz ***@***.*** 
Gesendet: Samstag, 27. März 2021 08:43
An: VitaeTeam/Vitae
Cc: gahartenstein; Author
Betreff: Re: [VitaeTeam/Vitae] no syncronisation on vitae core wallet V: 4.5.1 (#104)

 

Use version 4.6.2 now.

**Comment by vitaeuk1** [comment]
Thank you Gunter, but the problem was made by me. All fixed now.
Appreciate your response 🙏
