### ISSUE TITLE
problem password after last updat 4.6.2

### ISSUE THREAD

**Issue by Patjenolmans** [VitaeTeam/Vitae#106]
I have the same problem with my masternode : 1 mn runs, the other is invisible. Nodehub.io says that I have te restart my second mn but since the update (4.6.2) **I can't do anything : my password isn't being recognized anymore !**
I receive the message 
"Assertion failed! Program: C:\Program Files\Vitae\vitae-qt.exe File: crypter.cpp, line 249 Expression: false"

I can't do anything for the moment. What can I do to solve this problem ?

**Comment by kalilinuxoo7** [comment]
You can try starting your MN using old version of wallet.

**Comment by squidicuzz** [comment]
> You can try starting your MN using old version of wallet.

That won't work at all... Only version 4.6.2 and above is valid now, plus that isn't even the issue.

-----

> I have the same problem with my masternode : 1 mn runs, the other is invisible. Nodehub.io says that I have te restart my second mn but since the update (4.6.2) **I can't do anything : my password isn't being recognized anymore !**
> I receive the message
> "Assertion failed! Program: C:\Program Files\Vitae\vitae-qt.exe File: crypter.cpp, line 249 Expression: false"
> 
> I can't do anything for the moment. What can I do to solve this problem ?

This is the code from line 249...
```cpp
        if (keyPass && keyFail) {
            LogPrintf("The wallet is probably corrupted: Some keys decrypt but not all.");
            assert(false);
        }
```

Your `wallet.dat` is corrupt.  You will need to use a backup of it.

If all backups are corrupt, you will have to run a manual recovery over it.  There is an updated (works for Vitaes) recovery App here: https://github.com/squidicuzz/pywallet

**Comment by Patjenolmans** [comment]
Thx squidicuzz it works perfect now !
