### ISSUE TITLE
HELP !!

### ISSUE THREAD

**Issue by vitaeuk1** [VitaeTeam/Vitae#107]
Hello
This might seem like a very minor issue, but I need some help as I know nothing.

I have had some issues with my Mac which meant that I could not do the update of the latest Vitae Core wallet v4.6.2, plus the old version got deleted.

I have now upgraded to Big Sur and installed the new Vitae Core Wallet to my desk top.

IF I take the back up from my hard drive and put it on my desk top, will the information migrate automatically from the back up to the new update v4.6.2. ???

**Comment by kalilinuxoo7** [comment]
Yeah, definitely. Make sure to place your wallet.dat and FN/MN config files to the data directory
