### ISSUE TITLE
wallet does not record transaction history

### ISSUE THREAD

**Issue by Cantrieudo1981** [VitaeTeam/Vitae#137]
use Wallet version 4.6.5 for Mac
I send vitaetoken - wallet does not record transaction history
this sucks - how to control and track the transfers

**Comment by 2a5A1Ghu1** [comment]
It could be possible you forked off chain. Please check that you are the correct chain, if the issue still persists please post it here.

**Comment by Cantrieudo1981** [comment]
> It could be possible you forked off chain. Please check that you are the correct chain, if the issue still persists please post it here.

Transaction 1005 Vitae coin still arrives - but the wallet doesn't save and display the information of that transaction (causes me to do the transaction a second time) which is very very bad.
Thank Core DEV
