### ISSUE TITLE
Vitaecore big error

### ISSUE THREAD

**Issue by Cantrieudo1981** [VitaeTeam/Vitae#140]
Withdrawing vitae from Stex exchange to Viatecore does not receive Vitae.

1. Exchange reported that the order has been executed successfully
2. Rerun Vitaecore, delete the Blockchain local folder
3. https://explorer.vit.tips/ check ID payment error

Haven't found a way to fix the problem yet

**Comment by 2a5A1Ghu1** [comment]
You have to resync
