### ISSUE TITLE
Big Error

### ISSUE THREAD

**Issue by Cantrieudo1981** [VitaeTeam/Vitae#141]
<img width="560" alt="Screen Shot 2021-12-04 at 3 35 42 PM" src="https://user-images.githubusercontent.com/81286345/144716276-bb34dac7-6dcb-40b4-a36f-93c8a74336cc.png">
![Uploading Screen Shot 2021-12-02 at 9.38.21 PM.png…]

**Comment by Cantrieudo1981** [comment]
<img width="787" alt="Screen Shot 2021-12-03 at 4 44 29 PM" src="https://user-images.githubusercontent.com/81286345/144716320-e62ddbea-cec2-4fd3-8882-a9ef0f95504f.png">

**Comment by 2a5A1Ghu1** [comment]
needs a resync

**Comment by Cantrieudo1981** [comment]
> cần đồng bộ lại
Does our Blockchain system still create stable blocks, Sharks
