### ISSUE TITLE
Big Error???

### ISSUE THREAD

**Issue by Cantrieudo1981** [VitaeTeam/Vitae#142]
<img width="785" alt="Screen Shot 2021-12-02 at 9 38 21 PM" src="https://user-images.githubusercontent.com/81286345/144753858-070d5a40-49e8-4543-a806-2e0a18d3e394.png">

**Comment by Cantrieudo1981** [comment]
<img width="753" alt="Screen Shot 2021-12-05 at 10 55 59 PM" src="https://user-images.githubusercontent.com/81286345/144753880-b575fe49-3d40-4eaa-9b7c-d4e22a074971.png">
https://vitae.space

**Comment by 2a5A1Ghu1** [comment]
repeat of https://github.com/VitaeTeam/Vitae/issues/141

Vitae does not run the above services if you are having an issue with a forked wallet please resync.

**Comment by Cantrieudo1981** [comment]
> 

Yes - Big Thank Sir - Wearevitae.org
https://twitter.com/hongcan007
https://www.facebook.com/groups/vitaevn/permalink/1227061654450636/
