### ISSUE TITLE
I can't sync 4.7.0 . wallet successfully

### ISSUE THREAD

**Issue by Cantrieudo1981** [VitaeTeam/Vitae#151]
I can't sync 4.7.0 . wallet successfully
I selected: Repair Wallet
- delete all local blockchain folder
after 1 day: Syschonization failed "again and again"

<img width="1064" alt="Screen Shot 2022-05-25 at 06 49 57" src="https://user-images.githubusercontent.com/81286345/170150382-ee60735b-c608-4bf6-b36d-15f21ca79106.png">
<img width="583" alt="Screen Shot 2022-05-25 at 06 50 15" src="https://user-images.githubusercontent.com/81286345/170150373-460f4673-7471-4825-91b5-75cfb732a604.png">
<img width="1064" alt="Screen Shot 2022-05-25 at 15 37 38" src="https://user-images.githubusercontent.com/81286345/170219585-d1aed911-c9ab-4396-a50f-0e10633f148b.png">

**Comment by SeqSEE** [comment]
![image](https://user-images.githubusercontent.com/15011102/170172983-be873a50-02be-433e-bb09-fac0390d6105.png)

It seems like you are running the wrong version of the wallet. You can find 4.7.0 release here: https://github.com/VitaeTeam/Vitae/releases/tag/v4.7.0

**Comment by Cantrieudo1981** [comment]
[vitae-4.7.0-osx-catalina-unsigned.dmg](https://github.com/VitaeTeam/Vitae/releases/download/v4.7.0/vitae-4.7.0-osx-catalina-unsigned.dmg)
92.9 MB
26 days ago

I can't sync 4.7.0 . wallet successfully
I selected: Repair Wallet
- delete all local blockchain folder
- 24h past, i have 13 Peers connected
but "Sysnchronization failed" again and again

( I was try all of 4.7.0 release for Mac )
What can i shout do Dev VitaeTeam ???
Help 

<img width="582" alt="Screen Shot 2022-05-25 at 15 05 19" src="https://user-images.githubusercontent.com/81286345/170213020-bd329a4a-b7d4-4d56-b8f9-bcb2d02ee270.png">
<img width="1067" alt="Screen Shot 2022-05-25 at 15 16 43" src="https://user-images.githubusercontent.com/81286345/170215309-c58fcc05-bef3-4918-9160-f8644699068d.png">
<img width="480" alt="Screen Shot 2022-05-25 at 15 22 53" src="https://user-images.githubusercontent.com/81286345/170216459-dbfd2021-5998-4bf0-a4b3-b407e0017e24.png">
<img width="683" alt="Screen Shot 2022-05-25 at 15 29 09" src="https://user-images.githubusercontent.com/81286345/170217774-37aea51a-5154-4728-bd21-870e5e7023e0.png">
<img width="1060" alt="Screen Shot 2022-05-25 at 15 31 42" src="https://user-images.githubusercontent.com/81286345/170218246-8bc26d98-c691-404a-8626-2500b62bfcd2.png">

**Comment by Cantrieudo1981** [comment]
50 MasterNode + 13 Peers but Synchronization failed again and again
<img width="1440" alt="Screen Shot 2022-05-25 at 15 41 43" src="https://user-images.githubusercontent.com/81286345/170220549-61814360-d161-4f4c-8cee-58e04bf444a5.png">

**Comment by SeqSEE** [comment]
If you were running the older version of the wallet, you may have unintentionally banned the good 4.7.0 peers. 

Did you try to clear your banlist.dat and peers.dat before resyncing? If you haven't I would try removing those and performing the resync.

**Comment by Cantrieudo1981** [comment]
I banned peers of Micheal's Wallet vertion - dear Sir

**Comment by Cantrieudo1981** [comment]
> If you were running the older version of the wallet, you may have unintentionally banned the good 4.7.0 peers.
> 
> Did you try to clear your banlist.dat and peers.dat before resyncing? If you haven't I would try removing those and performing the resync.

I changed to another Macbook - all synced, I'm trying the bonus bet
Thank for Help
