### ISSUE TITLE
infection threat? 

### ISSUE THREAD

**Issue by chris-008** [VitaeTeam/Vitae#17]
Hi Guys,
While trying to install the Vitae wallet on my Macbook Pro (OS Mojave) , I got some warnings from my Avast scanner:

<img width="323" alt="schermafbeelding 2018-10-03 om 23 30 53" src="https://user-images.githubusercontent.com/32146240/46440747-a2653980-c764-11e8-82e9-e9831584a1a3.png">

anything to worry about?
rgrds,
Chris

**Comment by buddilla** [comment]
It is a false positive, this is a common issue for crypto wallets in general and this issue happens on windows systems(windows defender) more often than mac. In fact this is the first time I have seen a false positive for a mac wallet in a long time.

Remember though, this does not mean that some wallets are not malware of some type so it is always good to ask, just like you did.

Hope you are enjoying the new macOS, first thing I did was put it in dark mode my eyes are thanking me for that one. :)

I will leave this open for a day or two, so if you have other issues just use this thread.

**Comment by chris-008** [comment]
Hi, 
ok, thanks for the feedback.
Indeed the dark team makes a difference at night :-)
