### ISSUE TITLE
Wallet not working on Ubuntu 18

### ISSUE THREAD

**Issue by youstable** [VitaeTeam/Vitae#19]
I have setup Vitae on Ubuntu 18 but it is not working, it takes hours to sync and load nothing after completion

**Comment by squidicuzz** [comment]
Could you post more details please, check your debug.log for what is happening

**Comment by buddilla** [comment]
Is this still an issue?

Did you compile the wallet yourself or did you download the portable binary from our website?

**Comment by buddilla** [comment]
closing due to lack of response
