### ISSUE TITLE
Wrong link for Linux Daemon

### ISSUE THREAD

**Issue by jesobreira** [VitaeTeam/Vitae#20]
At [this page](https://vitaetoken.io/#wallet), we have both the Linux QT and Linux daemon links pointed to:

```
https://github.com/VitaeTeam/Vitae/releases/download/4.3.0/vitae-4.3.0-linux-64-qt.tar.gz
```

When, actually, the latter should be:

```
https://github.com/VitaeTeam/Vitae/releases/download/4.3.0/vitae-4.3.0-linux-64.tar.gz
```

As a sidenote, at [this document](https://www.vitaetoken.io/guide/Masternode_for_Vitae.pdf), the link for the daemon points to a 404 error page:

```
http://gir.sqdmc.net/vitae-linux.tar.gz 
```

**Comment by buddilla** [comment]
Resolved with last update...
