### ISSUE TITLE
Money Supply

### ISSUE THREAD

**Issue by JamT04D** [VitaeTeam/Vitae#33]
Various explorers stating different figures for how much Vitae is produced. Whats the correct number for the supply metrics? There's a big difference between 18M and 66M.

**Comment by squidicuzz** [comment]
18M Supply is the correct one.  Most of the explorers should be showing around that now.

`getinfo` will show 66M though, which is wrong.  We are working on fixes for this.

**Comment by buddilla** [comment]
We have this almost fixed, I believe it is due to an accumulator checkpoint issue. Next version should have this fixed. If the issue continues after the next update please feel free to reopen the issue.
