### ISSUE TITLE
Block time is really fast

### ISSUE THREAD

**Issue by SeqSEE** [VitaeTeam/Vitae#93]
Hey I am sure you know because it has been brought up. I am wondering if there was any progress in fixing the Vitae blockchain as no announcements have been made on social media about it. I figured the best place to ask would be the developers. Thanks!
![image](https://user-images.githubusercontent.com/15011102/108610324-d62b7300-73a2-11eb-8d60-50b6afe06678.png)

**Comment by tohsnoom** [comment]
Yes we were aware of it and it should be fixed now.

Please note that with the new time protocol, the block times are limited to 15 second intervals. With the target being 45 seconds, that means there are only two possibilities for speeding up the block time (15 or 30 seconds) and unlimited possibilities for slowing it down (e.g., sometimes there might be a 2 minute+ block time). With that kind of dynamic, what you would expect to see is a few long block times, some at 45 seconds, and a large number of 15 and 30 second blocks.

I will close this issue, but please reopen it and let me know if you are still seeing block times shorter than 45 seconds on average.
